DATA_PATH = "../datasets/standard-data.txt"  # Training Data Path
MODEL_PATH = "../trained models/basic_stonix" # Model Parameter Path
EMBEDDING_DIM = 256 #size of the vector used to represent each character (higher: better relationship understanding but longer training)
HIDDEN_SIZE = 512 #context understanding (higher: better context understanding but slower training)
LEARNING_RATE = 0.005 #rate which modifies the weight (higher: faster training but overshoot)
NUM_EPOCHS = 1 #number of iterations of the training data (higher: better training but longer training)
TEMPERATURE = 0.8 #creativeness
USE_CUDA = True #only set this True if your GPU supports CUDA and the right drivers are installed
START_TOKEN = "<SOS>" # Start of Sequenz
END_TOKEN = "<EOS>" # End of Sequenz
UNKNOWN_TOKEN = "<UNK>" # Unknown Symbol
PADDING_TOKEN = "<PAD>" # Sequenz Padding